### PR TITLE
Fix typo in german translation

### PR DESCRIPTION
**Pull request by Dudeplayz**
Fix typo: `eigene Ermessen` -> `eigenen Ermessen`

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Dudeplayz Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by Dudeplayz** [comment]
@alexandrtovmach I am a native speaker. But I am now unsure if it should be `eigenem Ermessen` instead. I will look for someone who can review this.

**Comment by alexandrtovmach** [comment]
> I will look for someone who can review this.

Thanks, we cannot accept any change with self-proofreading, because it's really danger :shrug:

**Comment by alexandrtovmach** [comment]
@futape @kewang @benbalter Could you help?

**Comment by futape** [comment]
`Nach deinem eigenen Ermessen` is correct.

**Comment by alexandrtovmach** [comment]
@futape Thanks for review 👍

**Comment by Dudeplayz** [comment]
@futape are you sure? I was thinking about `Nach deinem eigenem Ermessen`, so with `m` instead of `n`?

**Comment by futape** [comment]
@Dudeplayz I'm pretty sure, yes.

**Pull request merged**
