### PR TITLE
Slovak Translation: Declension - Fix form

### LINKED ISSUE #321: Slovak translation: Declension - non-preferred form
Semantic Versioning is translated as Semantické verziovanie, from the word version -> verzia. The "i" is dropped in the current translation version.

### PR DESCRIPTION
**Pull request by kubo6472**
Closes #321

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@tiso @ujovlado @ujovlado could you review?

**Comment by alexandrtovmach** [comment]
Friendly reminder

**Comment by kubo6472** [comment]
> Friendly reminder

Will there be an unfriendly reminder? I doubt any of those guys are active anymore and if you look, it's just a small change because in our language it is not defined, how we should translate the word versioning, but the form used was the less common one, so I suggested a change to the more used form. You can do a quick check with a Google translator as well, since both of those forms translate correctly.

**Comment by alexandrtovmach** [comment]
@kubo6472 I see your point, but unfortunately it's not allowed. Just try to understand, if this word somehow can be translated in a wrong way, some jargon etc. it'll be bad case for spec. So this formal process, it's something required. :shrug: 

Maybe @rootpd, @Cyril-the-Real, @Jardo-51 can help?

**Comment by kubo6472** [comment]
Yep, ofc I understand. I'm just trying to explain in detail what this PR is trying to achieve. I use semver on 90% of my projects, where this is applicable, so I certainly wouldn't wanna damage it's translation :)

**Review by rootpd — APPROVED** [review]
Checked, the change seems to be valid. Even though I wouldn't probably bother with the change, I see couple of reliable sources using the proposed variant of the translation.

Couple of sources I used to cross-check this:

- https://education.microsoft.com/sk-sk/course/a1f2b45f/2
- https://www.ibm.com/docs/sk/ssw_aix_72/com.ibm.aix.wpar/cre-kickoff.htm
- https://jazykovaporadna.sme.sk/h/verzovanie/13862/
- https://tortoisesvn.net/docs/release/TortoiseSVN_sk/tsvn-basics-versioning.html
- https://www.facebook.com/WebSupport.sk/posts/vyu%C5%BE%C3%ADvate-pre-verziovanie-svojej-str%C3%A1nky-git-alebo-by-ste-chceli-zauj%C3%ADma-v%C3%A1s-%C4%8Di-/10154199264867142/

**Comment by alexandrtovmach** [comment]
@rootpd @kubo6472 Thanks for contribution

**Pull request merged**
