### PR TITLE
Fix Chinese translation (zh-TW and zh-CN)

### PR DESCRIPTION
**Pull request by zetaraku**
The translation of `SHOULD` in **lang/zh-TW** is wrong.
It should be "應該 (should)" instead of "可 (may)".

The same problem is also found in **lang/zh-CN** but I'm unable to fix it.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@zetaraku Thank you for contribution! For translations content we require to have at least one native speaker review. Could you assign someone to handle that?

**Comment by zetaraku** [comment]
@alexandrtovmach Does the person need to be a contributor to this repository or just any native speaker user is fine?
Maybe we can just assign it to one of the contributors to this file.

**Comment by alexandrtovmach** [comment]
Of course, "be a contributor to this repository" it's better, but "any native speaker user is fine"

**Comment by zetaraku** [comment]
@alexandrtovmach Since I'm neither having write access nor a contributor yet, can you assign a member from the original translation contributors for me?

**Comment by alexandrtovmach** [comment]
@wmh @danny0838 @kewang @benbalter
Could you take a look?

**Review by kewang — APPROVED** [review]

**Comment by zetaraku** [comment]
@alexandrtovmach Let's wait for the zh-CN translation and fix them altogether :)

**Review by danny0838 — APPROVED** [review]

**Comment by wmh** [comment]
我比較偏好原本的版本，讀起來比較順暢。

**Comment by danny0838** [comment]
I agree with this change as it's more consistent with the SHOULD used other where in the same document anyway.

A few further issues:

1. Other SHOULD occurrences are not emphasized equally as other keywords do.

2. I think it would better to translate these RFC2119 keywords with referenced English keywords only once and use them in latter occurrences without the original English keyword. If there were to be somewhere this translation can't fit well due to grammar difference, we can use another translation with original English keywords provided.

Though these can be included in another PR.

**Comment by danny0838** [comment]
> 
> 
> 我比較偏好原本的版本，讀起來比較順暢。

恕不同意。我認為把 should 翻成「可」是語意上的錯誤，這遠比通不通順更嚴重。

如果考慮通順的問題，我傾向把 SHOULD 譯為「宜」（「應」對應 SHALL）。但是這個要改就是要進一步的整個文件一起改了。目前這個部分先單獨改就好。

**Comment by danny0838** [comment]
I found that there's been a recent change in the English version that has shifted the "SHOULD" to "MUST". Maybe we can skip discussion on this issue and go #299 directly.

**Comment by zetaraku** [comment]
This problem seems to be solved already. Maybe this PR can be closed now?

**Pull request closed without merging**
