### PR TITLE
Add SemVer v2.0.0-rc.1 and v2.0.0  Portuguese-Brazilian translation

### PR DESCRIPTION
**Pull request by walkeralencar**
As comments at https://github.com/mojombo/semver/issues/184

Follow v2.0.0 and v2.0.0-rc.1 of Brazilian Portuguese translation

Updated all need files.

### CODE REVIEW

**Comment by lfilho** [comment]
:+1:
I'd be glad to help with this in the future as well.
I say ship it! :shipit:

**Comment by lfilho** [comment]
@mojombo any thoughts on this one? I'm just implanting this in my team and would be lovely to pass the reference to them in our native language...

**Comment by haacked** [comment]
I have no way to review this as I don't know Portugese but if you think it looks good, I'll have to trust that. :)

**Comment by lfilho** [comment]
:+1: thanks!

**Pull request merged**
