### PR TITLE
Added romanian translation.

### PR DESCRIPTION
**Pull request by kinkod**

### CODE REVIEW

**Comment by kinkod** [comment]
This is the first time I am doing a pull request on GitHub. Please let me know if everything is ok with the pull request and what i have submitted or what I need to fix. Thank you.

**Comment by alexandrtovmach** [comment]
@kinkod thanks for your contribution, we really appreciate :hugs: and congratulations with your first PR :partying_face:  
Could you find another Romanian native speaker, and ask to review your changes?

**Comment by kinkod** [comment]
We were a team of multiple translators and we cross checked. Can't vouch there are zero mistakes but we did our best.

**Comment by alexandrtovmach** [comment]
Sounds good 😊 but for translations content we require to have at least one native speaker review. It's may sound a bit weird, especially if you already did cross-check inside your team. That's need to be sure (as much as we can) that's no any violation.

Could you assign someone to handle that, maybe from your team?

**Review by codatorproducator — APPROVED** [review]
este bun

**Comment by alexandrtovmach** [comment]
Okay, so @codatorproducator seems like really fresh account. I'd ask for one more review from someone more "old" on GitHub. Do you have someone?

**Comment by dgmmarin** [comment]
:)Seems ok

**Comment by alexandrtovmach** [comment]
@kinkod @dgmmarin @codatorproducator thank you :partying_face:

**Comment by alexandrtovmach** [comment]
https://semver.org/lang/ro/

**Pull request merged**
