### PR TITLE
fix: Splitted and updated workflows

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Review by indirect — APPROVED** [review]
Looking good 😄

**Comment by alexandrtovmach** [comment]
@indirect Please add rule to require for approval from github-bot

**Comment by indirect** [comment]
Enabled "1 approving review required to merge" 👍

**Comment by alexandrtovmach** [comment]
I've used next workaround with GH Actions limitations:
- linter check runs automatically and we have rule that require passing `checks`
- protecting content checks triggers by `/check` and result will be a review from `github-bot`:
    - if okay, they will approve it
    - if not, request changes in files that's not expected to be updated here

**Comment by alexandrtovmach** [comment]
@indirect Sorry, could you set 2 required approvals. because one is for bot, but another should be for human. Or we don't want to make rules so strict?

**Comment by indirect** [comment]
¯\\_(ツ)\_/¯ either one seems ok to me. I'll set it to 2 for now, and we can see if that becomes annoying.

**Comment by alexandrtovmach** [comment]
@indirect Great, thank you for quick help

**Pull request merged**
