### PR TITLE
Hebrew - add faq 

### LINKED ISSUE #274: Spelling errors
In the Hebrew version, SHALL is misspelled "SHELL".

### PR DESCRIPTION
**Pull request by YanivD**
Thank you for describing the Semantic Versioning specification also in the Hebrew language!

This PR adds translation for 2 missing frequently asked questions. Also, fixed [reported typo](https://github.com/semver/semver.org/issues/274).

### CODE REVIEW

**Comment by YanivD** [comment]
@alexandrtovmach 
can you review / approve?

**Comment by alexandrtovmach** [comment]
I can merge with at least one approval from native speaker. Could you find someone for it?

**Comment by blumamir** [comment]
Hi, I'm a native Hebrew speaker and approve these changes

**Review by blumamir — APPROVED** [review]

**Comment by nirsky** [comment]
I'm also a native Hebrew speaker - LGTM!

**Review by nirsky — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
Thanks everyone for contribution :clap:

**Pull request merged**
