### PR TITLE
Fix Japanese wording consistency and typo

### PR DESCRIPTION
**Pull request by seratch**
If you need Jpapanese reviewers, please let me know.

### CODE REVIEW

**Comment by haacked** [comment]
@seratch Sorry for the late reply. I do need Japanese reviewers.

**Comment by seratch** [comment]
@Haacked Thank you for your reply! I'll ask someone to review this change. One moment, please.

**Comment by ma2gedev** [comment]
LGTM!

**Comment by tkawachi** [comment]
LGTM

**Comment by morizyun** [comment]
LGTM :+1:

**Comment by seratch** [comment]
I asked my friends to review this PR. Thanks all.

I believe this PR is safe enough. Because that fixes an expression to be more formal and a small typo (semvar).

**Comment by haacked** [comment]
ありがとう

**Comment by seratch** [comment]
シッ...... ヨッシャー！ :smiley:

**Pull request merged**
