### PR TITLE
First commit of Dutch translation, SemVer spec 2.0.0

### PR DESCRIPTION
**Pull request by niekvangalen**
My first try on a Dutch translation of the SemVer spec, version 2.0.0. Ready for (a hereby requested) review.

### CODE REVIEW

**Review by ahenket — CHANGES_REQUESTED** [review]
Submitted change proposal for updates in https://github.com/niekvangalen/semver.org/pull/1

**Comment by niekvangalen** [comment]
This translation is written by me (native speaker in Dutch) and reviewed by two native speakers.
@alexandrtovmach can you take a look at this pull request?

**Comment by alexandrtovmach** [comment]
Sorry for long response, was busy with 2020 =)

**Review by alexandrtovmach — APPROVED** [review]

**Pull request merged**
