### PR TITLE
Fix typos in the Hungarian translation

### PR DESCRIPTION
**Pull request by junpet**

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@junpet Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by junpet** [comment]
@alexandrtovmach I'm native speaker. Unfortunately I don't know anyone else, I'm a lone wolf.

**Comment by alexandrtovmach** [comment]
@junpet Don't give up 😄 You can ask your friends, or find reviewers on some local developer forums. I actually did in the same way for Ukrainian and Russian translations. Probably it works for you

**Comment by alexandrtovmach** [comment]
@juliacodez @koviroli Could you help?

**Comment by koviroli** [comment]
Hi, here I am. :)

**Comment by alexandrtovmach** [comment]
@koviroli Could you review this changes?

**Comment by koviroli** [comment]
Yes, I am going to review it right now.

**Review by koviroli — APPROVED** [review]
Seems good!

**Comment by alexandrtovmach** [comment]
@koviroli thanks

**Comment by junpet** [comment]
Thanks!

**Pull request merged**
