### PR TITLE
Fix typos in swedish translation

### PR DESCRIPTION
**Pull request by Krisell**
Also updates some wording.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Krisell Thanks for contribution. Do you know any native speaker who can review these changes?

**Review by Johannestegner — APPROVED** [review]
LSTM (looks swedish to me!)

This PR does increase the readability of the document in Swedish (and yes, I am Swedish).

**Review by martindanielsson — APPROVED** [review]
I also agree, this is correct.

**Comment by alexandrtovmach** [comment]
@Johannestegner and @martindanielsson thank you for review 👍

**Pull request merged**
