### PR TITLE
Slovenian translation added

### PR DESCRIPTION
**Pull request by petk**
Hello, I'm proposing adding the Slovenian translation (sl_SI) as well. SemVer v2.0.0 translated and reviewed/re-read few times by me. Local installation works fine as well. If we need another review-er I maybe get someone else to check it out but there should be everything working ok. I'm also planning to add patches when English origin gets updated. Thanks for considering adding it to semver.org. Kind regards, Peter.

### CODE REVIEW

**Comment by petk** [comment]
Just bumping pull request. @Haacked let me know, please if there is anything stopping this pull request from being merged into the main repository. Thank you.

**Comment by haacked** [comment]
@peterkokot can you have someone else review the translation and comment here? I'm not capable of reviewing Slovenian. :smile:

**Comment by petk** [comment]
Ok, wait. I'll find some Slovenian reviewer to check the translation. Thank you.

**Comment by alsar** [comment]
I've checked the translation and it's ok.

**Comment by petk** [comment]
Ping @Haacked: Maybe this would be now good to merge? Thanks to @alsar translations is now checked. I've also rebased this so it can be automatically merged in the main repo's gh-pages branch. Thank you.

**Pull request merged**
