### PR TITLE
translate to turkish

### PR DESCRIPTION
**Pull request by inancgumus**
You can let me know for the problems, if any, from [here](http://www.twitter.com/inancgumus) or from this thread.

@mojombo @mathiasbynens fyi. thanks.

### CODE REVIEW

**Comment by inancgumus** [comment]
@mojombo @mathiasbynens is anybody out there???

**Comment by haacked** [comment]
Hi there! I was on vacation so I didn't see this until now. Can you find someone to check your work? I am not able to verify the translation.

**Comment by inancgumus** [comment]
Umm, ok, no problem, is that person can be anyone? @Haacked

**Comment by haacked** [comment]
> Umm, ok, no problem, is that person can be anyone? @Haacked

Anyone who speaks Turkish. :smile:

**Comment by inancgumus** [comment]
@kivancgumus can you review this for me please?

**Comment by kivancgumus** [comment]
@Haacked  i have read all of it and it's ok. 

Good work @deeperx 

Türkçe Meali: Bence çok güzel tercüme etmiş  :)

**Comment by haacked** [comment]
selfie-0

**Pull request merged**
