### PR TITLE
Translation/bulgarian

### PR DESCRIPTION
**Pull request by atsonkov**
Adds Bulgarian translation of SemVer 2.0.0

### CODE REVIEW

**Comment by atsonkov** [comment]
Native speaker reviewers may be @OrlinVasilev or @spanev

**Comment by alexandrtovmach** [comment]
@atsonkov Thanks for contribution 👍 
@OrlinVasilev @spanev Would you help with review?

**Comment by OrlinVasilev** [comment]
@atsonkov @alexandrtovmach  looks good to me !

**Review by OrlinVasilev — APPROVED** [review]
Looks good to me!!

**Comment by alexandrtovmach** [comment]
@OrlinVasilev Thanks for review :+1:

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@atsonkov Could you [make your branch up-to-date](https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch#:~:text=make%20sure%20you've%20checked%20out%20your%20branch%3A%20git%20checkout,of%2Ddate%20is%20blocking%20your)? There is something weird, because I can't do this by my own from UI :confused:

**Comment by alexandrtovmach** [comment]
Closing to re-open :warning:

**Comment by alexandrtovmach** [comment]
@atsonkov One more thing, please fix linter errors

**Comment by atsonkov** [comment]
I will update the branch and will need to check what do I need to change to fix the lint.

**Comment by alexandrtovmach** [comment]
@atsonkov Linter errors are about fenced code blocks. If you didn't translate **"Backus–Naur Form Grammar for Valid SemVer Versions"** code block, you can simply copy/paste it with formatting from [original md file](https://raw.githubusercontent.com/semver/semver.org/gh-pages/spec/v2.0.0.md).

Use `npm run lint` to test locally.

**Comment by atsonkov** [comment]
@alexandrtovmach Should be ready to be merged now.

**Comment by alexandrtovmach** [comment]
Thanks everyone for contributions! :rocket:

**Comment by alexandrtovmach** [comment]
It's live now: https://semver.org/lang/bg/

**Pull request merged**
