### PR TITLE
🇺🇦 Ukrainian translation improvements

### PR DESCRIPTION
**Pull request by satelllte**
## Improvements

- Added [RFC 2119](https://tools.ietf.org/html/rfc2119) hyperlink
- Added Backus-Naur form grammar section
- Added FAQ => `Is "v1.2.3" a semantic version?` section
- Added FAQ => RegEx section

### CODE REVIEW

**Comment by JohnTitor** [comment]
@shatokhinvlad Seems you updated the Ukrainian translation in the past, could you review this PR?

**Comment by shatokhinvlad** [comment]
> @shatokhinvlad Seems you updated the Ukrainian translation in the past, could you review this PR?

@JohnTitor Maybe Backus normal form (BNF) `<symbols>` should be translated too?

**Comment by JohnTitor** [comment]
> Maybe Backus normal form (BNF) `<symbols>` should be translated too?

IMO it shouldn't be as BNF itself is one of metasyntax. Actually, many languages don't translate them (except for Korean and Spanish, at a quick glance). But if translating it makes sense in Ukrainian, I don't mind if they're translated.

**Comment by shatokhinvlad** [comment]
> IMO it shouldn't be as BNF itself is one of metasyntax.

It makes sense. So let`s leave it as is.

**Review by shatokhinvlad — APPROVED** [review]
Quality translation.

**Comment by JohnTitor** [comment]
@satelllte Could you fix the lint failure? I recently updated dependencies so rebasing may be required.

**Comment by satelllte** [comment]
@JohnTitor fixed 🔨

**Review by JohnTitor — APPROVED** [review]
Thanks for translating!

**Pull request merged**
