### PR TITLE
docs: update Vietnamese translation

### PR DESCRIPTION
**Pull request by lamngockhuong**
## Description

- Make the content be readable and smoother.
- Fix some typos.

## PR Checklist

- [x] This PR doesn't modify the files in the `spec` dir.
- [x] This PR passes `npm run lint`.
- [ ] (Optional) If you're willing to help reviews about your language's translations, add your name to the `TRANSLATORS.md`.

### CODE REVIEW

**Comment by JohnTitor** [comment]
@ntk148v Could you review this PR? I'm not a Vietnamese speaker and need a reviewer.

**Comment by ntk148v** [comment]
@JohnTitor let me take a look 👍🏼

**Review by ntk148v — APPROVED** [review]
💯

**Review by JohnTitor — APPROVED** [review]
Thank you both!

**Pull request merged**
