### PR TITLE
some Spanish enhancements

### PR DESCRIPTION
**Pull request by yajo**
"Deprecado" sounds very bad 😅

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@agustinf could you review?

**Comment by alexandrtovmach** [comment]
cc: @Sulfkain @DarkGhostHunter

**Comment by DarkGhostHunter** [comment]
Yeah. "Deprecar" means to pray/supplicate. Can't approve since it uses "release minor", as it should be "lanzar una versión menor".

**Comment by alexandrtovmach** [comment]
@Yajo could you negotiate?

**Review by agustinf — APPROVED** [review]

**Comment by yajo** [comment]
Actually I see that "major", "minor" and "patch" are used literally without need, and release is sometimes translated into "liberar", which would be good if we were releasing a bird, but for releasing software "lanzar" is better.

Let me do the changes.

**Review by DarkGhostHunter — APPROVED** [review]

**Comment by DarkGhostHunter** [comment]
Fixes accepted. Should be ready to go.

**Comment by alexandrtovmach** [comment]
@Yajo @DarkGhostHunter thanks for contribution

**Comment by 72073** [comment]
How are you

**Pull request merged**
