### PR TITLE
Update v2.0.0.md

### PR DESCRIPTION
**Pull request by Cyril-the-Real**

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Cyril-the-Real Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by Cyril-the-Real** [comment]
> @Cyril-the-Real Thanks for contribution. Do you know any native speaker who can review these changes?

@ujovlado, @tiso, @rootpd, @Jardo-51

**Comment by rootpd** [comment]
Looks OK.

**Review by tiso — APPROVED** [review]
OK

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@tiso Thanks for review :+1:

**Pull request merged**
