### PR TITLE
[Japanese] Fix Japanese translation for slightly better expression

### PR DESCRIPTION
**Pull request by ohbarye**
I fixed Japanese translation for slightly better expression.

### CODE REVIEW

**Comment by klehelley** [comment]
While I am not a native Japanese speaker, I've been learning it for a few years now. From my knowledge of that language, the change proposed here seems sensible.

**Comment by alexandrtovmach** [comment]
@klehelley Thank you for your effort, really appreciate 🎉 💪 but I think it'll be better to have review from native speaker

@ohbarye Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by ohbarye** [comment]
> Do you know any native speaker who can review these changes?

@munierujp @haacked @soukouki @gulping @foomin10 
How about you? I saw you've reviewed or contributed to this project in Japanese.

**Comment by munierujp** [comment]
@alexandrtovmach @ohbarye It looks like a good fix :smile:

**Comment by alexandrtovmach** [comment]
@munierujp thanks for review

**Pull request merged**
