### PR TITLE
Propagate recent changes in index to v2.0.0 

### PR DESCRIPTION
**Pull request by danny0838**
Sync v2.0.0.md with index.md

### CODE REVIEW

**Comment by JohnTitor** [comment]
@hwhsu1231 Thank you for working on #401! Could you review this PR?

**Comment by hwhsu1231** [comment]
@JohnTitor - OK! I'll take some time to write my review these days.

**Comment by danny0838** [comment]
@JohnTitor  @hwhsu1231 Just a note: This PR has nothing fancy but simply a fix of previous d3191ef68a460243332cd7cec07d119a633286c7, d1389ac77700d45ab67d43a702e3d4c0435a968f, and 1d996e7316a87a5e9b66027170f2e045688e065b, which have missed to edit `lang/zh-TW/spec/v2.0.0.md`. This can be quickly confirmed by checking whether `lang/zh-TW/index.md` and `lang/zh-TW/spec/v2.0.0.md` are identical through diffing them.

**Review by JohnTitor — APPROVED** [review]
Ah sorry, I missed the message on the OP. LGTM :)

**Pull request merged**
