### PR TITLE
Update FAQs in Korean documents

### PR DESCRIPTION
**Pull request by AndersonChoi**
Add translated FAQ items
- Is "v1.2.3" a semantic version?
- Is there a suggested regular expression (RegEx) to check a SemVer string?

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@AndersonChoi Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by AndersonChoi** [comment]
@alexandrtovmach I recommend @tucan9389 as a reviewer. He is an iOS developer in South Korea and has a deep understanding of semver.

**Review by tucan9389 — APPROVED** [review]
👍 LGTM

**Comment by alexandrtovmach** [comment]
@tucan9389 Thank you for review :+1:

**Pull request merged**
