### PR TITLE
Add summary info in Spanish

### PR DESCRIPTION
**Pull request by Sulfkain**
Add summary info in Spanish like in English Version

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Sulfkain Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by Sulfkain** [comment]
I'm a native speaker from Spain :D.
Anyway if someone would like to check the changes or do any fix, will be appreciate.

**Comment by alexandrtovmach** [comment]
@Sulfkain For sure we need to have at least one more proofreader. Would you mention somebody here?

**Comment by Sulfkain** [comment]
@khelben5 Could you check this PR please

**Comment by alexandrtovmach** [comment]
@DarkGhostHunter could you help?

**Comment by DarkGhostHunter** [comment]
I can proof read this bit.

**Review by DarkGhostHunter — COMMENTED** [review]
No debería ser Español? MAYOR.MENOR.PARCHE-ETIQUETA.

**Comment by Sulfkain** [comment]
In all tech environments I know, the people tend to use English terms, like "scope" instead "ámbito", "Product Owner", "Death line" and so on.
The same with versioning, we use always "Major", "Minor", "Patch" and not "Mayor", "menor", "parche".

I prefer too to avoid english terms when needed, so 2 face on the same coin. Do you thing it's better to avoid english terms or to use the Facto use?

**Comment by DarkGhostHunter** [comment]
I think that it should be reserved only for software actions, since these do not vary and sometimes lose context when translated.

For example, "MAJOR VERSION" is easily translatable to "VERSIÓN MAYOR", but a git pull it's difficult to translate properly without adding overhead, like "git traer".

Also, and most importantly, if someone is reading SEMVER in spanish, then we should push neutral spanish whenever we can to make it undestandable without requiring further English knowledge apart from the software it may reference (like console commands).

**Review by Sulfkain — COMMENTED** [review]
Remove english terms

**Comment by Sulfkain** [comment]
> I think that it should be reserved only for software actions, since these do not vary and sometimes lose context when translated.
> 
> For example, "MAJOR VERSION" is easily translatable to "VERSIÓN MAYOR", but a git pull it's difficult to translate properly without adding overhead, like "git traer".
> 
> Also, and most importantly, if someone is reading SEMVER in spanish, then we should push neutral spanish whenever we can to make it undestandable without requiring further English knowledge apart from the software it may reference (like console commands).

Done, BUT, in the rest of the text, the terms used are IN ENGLISH, major, minor, path, so we need to change that part then too...

**Comment by DarkGhostHunter** [comment]
> > I think that it should be reserved only for software actions, since these do not vary and sometimes lose context when translated.
> > For example, "MAJOR VERSION" is easily translatable to "VERSIÓN MAYOR", but a git pull it's difficult to translate properly without adding overhead, like "git traer".
> > Also, and most importantly, if someone is reading SEMVER in spanish, then we should push neutral spanish whenever we can to make it undestandable without requiring further English knowledge apart from the software it may reference (like console commands).
> 
> Done, BUT, in the rest of the text, the terms used are IN ENGLISH, major, minor, path, so we need to change that part then too...

I don't think it would be good to have two different terms for the same concept on a procedure documentation. I mean, it should be consistent: all spanish, except of software behaviour (like console commands), or all english.

Since this should be pushing spanish where it can, I vote for the first approach. This shouldn't be confusing for somebody who is reading SEMVER for the first time, even a first time coder.

**Comment by Sulfkain** [comment]
So @alexandrtovmach , what we do?, I change my PR or @DarkGhostHunter PR?
I have posted some comments on @DarkGhostHunter PR.

**Comment by alexandrtovmach** [comment]
From my experience we should **NOT TRANSLATE** English terms in three cases:

1. There are no analogues in target language
2. Original word used not in usual meaning: `fork a repository`
3. Word is name / command in programming

Major, minor, patch - looks okay to translate everywhere around the project :+1:

**Comment by Sulfkain** [comment]
Yeah, that's clear :P.
The question is WHAT PR we modify? To do the job only on one site.

Or I modify this PR or @DarkGhostHunter modify his PR.

**Comment by alexandrtovmach** [comment]
@Sulfkain If your PR has _major, minor, patch_ translated, it seems correct for me, and seems like @DarkGhostHunter PR should be updated.

Meanwhile, thank you both for your contribution and effort 🥇 🥇

**Comment by alexandrtovmach** [comment]
You can merge both PR if all other updates looks okay, and then create one more PR with _major, minor, patch_ translation over the document

**Comment by Sulfkain** [comment]
If my PR seem ok to you, you should approved :D

I will create a new PR with replace terms in English

**Comment by alexandrtovmach** [comment]
Closed in favor of https://github.com/semver/semver.org/pull/240

**Pull request closed without merging**
