### PR TITLE
Fixing misspell in russian version

### PR DESCRIPTION
**Pull request by bessarabov**
https://github.com/mojombo/semver/issues/170

### CODE REVIEW

**Comment by haacked** [comment]
Thanks! Not knowing any Russian, I'll have to take your word for it. :)

:thumbsup:

**Comment by bessarabov** [comment]
@Haacked you haven't merged this PR. Maybe you just forgotten, or there is some other reason? The change is correct I swear =)

**Comment by haacked** [comment]
Doh! I must have bad aim and missed the green button. Done!

**Comment by bessarabov** [comment]
Super! Thank you! =)

**Pull request merged**
