### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Cyril-the-Real**

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Cyril-the-Real Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by Cyril-the-Real** [comment]
> @Cyril-the-Real Thanks for contribution. Do you know any native speaker who can review these changes?

@ujovlado, @tiso, @rootpd, @Jardo-51

**Comment by rootpd** [comment]
Looks good to me!

**Comment by alexandrtovmach** [comment]
@rootpd Thank you for review

**Review by alexandrtovmach — APPROVED** [review]

**Pull request merged**
