### PR TITLE
fix miss Japanese translation in section 9

### PR DESCRIPTION
**Pull request by iwaim**

### CODE REVIEW

**Comment by Sixeight** [comment]
:+1:

Should we need to fix "ja/index.md" too?

**Comment by haacked** [comment]
Probably. I can't merge this PR. Want to fix it up?

**Comment by Sixeight** [comment]
@Haacked thank you! I need to talk with author.

@iwaim We need both of `ja/index.md` and `lang/jp/spec/v2.0.0.md`. Could you fix it up this pull-request? or may I create new pull-request about this issue?

see also: https://github.com/Sixeight/semver.org/commit/9654614545f42f3259d6a3667c4f55a290101884

**Comment by Sixeight** [comment]
duplicate with #120

**Pull request closed without merging**
