### PR TITLE
Bulgarian translation improvements (#377)

### PR DESCRIPTION
**Pull request by atsonkov**
Update the bulgarian translation with terms that gain popularity in bulgarian and should make the meaning closer to the original.

### CODE REVIEW

**Comment by atsonkov** [comment]
@d78mdd, may I ask you to review this Pull request?

**Comment by JohnTitor** [comment]
@atsonkov Is there any other reviewer? If not, I'm fine to merge as-is.

**Comment by atsonkov** [comment]
@JohnTitor I also think it needs to pass peer review.

@OrlinVasilev @spanev May I ask you to review and approve the PR if you agree with the changes when you have some time?

**Comment by JohnTitor** [comment]
> I also think it needs to pass peer review.

If there is a reviewer, I think so. But it's also better than nothing, I'd prefer to merge over get it abandoned if a PR doesn't look spammy.

**Review by spanev — APPROVED** [review]
The changes look good to me and I agree with them.

**Review by JohnTitor — APPROVED** [review]
Thanks both!

**Pull request merged**
