### PR TITLE
[lang/cs] add spec file

### PR DESCRIPTION
**Pull request by nekomajin**

### CODE REVIEW

**Comment by haacked** [comment]
Thanks for the contribution! Could you help find other native czech speakers to review this?

**Comment by nekomajin** [comment]
@Haacked No problem :thumbsup: By the way: this is a copy from [lang/cs/index.md](https://github.com/mojombo/semver.org/blob/gh-pages/lang/cs/index.md). I'm searching for some native czech speakers.

**Comment by nekomajin** [comment]
@martinrotter @Kynio89 @jiripudil @hajovsky @ondras @jirikuchta @zdenektopic
Hello you. We need for this project Czech-speaking people. Would you please check whether the translation of [this file](https://github.com/mojombo/semver.org/blob/gh-pages/index.md) compared with [this](https://github.com/nekomajin/semver.org/blob/a1ce2b0dbcfbca488796457e92719132be8c39a5/lang/cs/index.md) and [this](https://github.com/nekomajin/semver.org/blob/a1ce2b0dbcfbca488796457e92719132be8c39a5/lang/cs/spec/v2.0.0.md) file (actually the same) is valid? You would help us so much further.

**Comment by haacked** [comment]
> By the way: this is a copy from lang/cs/index.md. I'm searching for some native czech speakers.

Oh! I see. I didn't check thoroughly and I thought this was a new translation. I'm happy to have others review the czech translation, but if this is just a copy, I'm fine with this.

**Comment by martinrotter** [comment]
Hello fellaz. Yep, I can and will check right now.

**Pull request merged**
