### PR TITLE
Fixed typo/wording in Swedish translation of specification

### PR DESCRIPTION
**Pull request by ManneW**
Changed to "lättvindigt", since this is the appropriate translation of "lightly".

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@ManneW Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by ManneW** [comment]
@alexandrtovmach I'll see if I can find someone 🙂

Just to be sure; it's not enough with myself being a native speaker and that the replaced word "lättvinnligt" isn't an "official" Swedish word? 😄

**Comment by alexandrtovmach** [comment]
Sorry, but we cannot accept any change with self-proofreading, because it's really danger :shrug:

**Comment by ManneW** [comment]
@alexandrtovmach Totally understand 👍 I just wanted to make sure 🙂I'll see what I can find 🔍

**Comment by alexandrtovmach** [comment]
@magol @jonatanskogsfors @benbalter Could you help?

**Comment by jonatanskogsfors** [comment]
Good change!

**Review by jonatanskogsfors — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@jonatanskogsfors thanks

**Comment by magol** [comment]
I approve the change

**Pull request merged**
