### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by okj579**
I've translated the 2.0.0 spec to German. Ideally, this still needs a native German-speaking proofreader.

### CODE REVIEW

**Comment by paulgoetze** [comment]
Well done so far! I reviewed your translation and sent a pull request on your fork (https://github.com/okj579/semver.org/pull/1).

**Comment by okj579** [comment]
Thanks @paulgoetze! Those all look like good changes. It does seem, however, that trying to make the RFC2119 keywords work in German is like hammering a square peg into a round hole (e.g. "DARF NICHT" vs. "KEINE führende Nullen enthalten DÜRFEN"). Instead of trying to force it to fit, I accepted all your changes and adjusted the explanation of the keywords instead.

**Comment by seisfeld** [comment]
I also proof read the german version. Sounds good to me as well! Good work @okj579 & @paulgoetze ! Hope this is merged soon.

**Comment by haacked** [comment]
Looks like the German translation is up. Please take a look and let me know if it's correct.

**Pull request closed without merging**
