### PR TITLE
Correct lang and dir in <html>

### PR DESCRIPTION
**Pull request by magol**
#154

### CODE REVIEW

**Comment by magol** [comment]
haha, look that Haacked was faster than me :-D

**Comment by haacked** [comment]
Unfortunately I'm having trouble testing mine out locally. 😦 Gotta update my Ubuntu VM. 😛

**Comment by haacked** [comment]
@magol I wonder if I should just hard-code the rtl languages like you did since there's only so many.

**Comment by magol** [comment]
> I wonder if I should just hard-code the rtl languages like you did since there's only so many.

@Haacked I think that your solution is clearly much better than mine. It is becoming clearer and avoids hard-coding, which provides more flexibility.

**Pull request closed without merging**
