### PR TITLE
[Japanese] fix: Copy lang/ja/index.md to lang/ja/spec/v2.0.0.md

### PR DESCRIPTION
**Pull request by foomin10**
In commit 4596410, I fixed index.md but forgot to fix spec/v2.0.0.md.

### CODE REVIEW

**Comment by foomin10** [comment]
links #208

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
Thanks for pay attention and fix

**Comment by foomin10** [comment]
Thank you for merge

**Pull request merged**
