### PR TITLE
Add Arabic translation

### PR DESCRIPTION
**Pull request by 01walid**
Hi, 

Finally finished the Arabic version, took me longer than expected :)

### CODE REVIEW

**Comment by haacked** [comment]
Great! Just need someone else more capable me to review this.

**Comment by 01walid** [comment]
You mean someone who understands Arabic ?

**Comment by haacked** [comment]
@01walid yup!

**Comment by 01walid** [comment]
Sure, 
Do you know any one up to the task? 

I can ask some folks I know to proofread it (some very well known ones in the MENA region)

**Comment by haacked** [comment]
I do not. Feel free to ask someone you know.

**Comment by 01walid** [comment]
Hi @Haacked, 

It's now reviewed by two more people, I believe it's in a pretty good shape :)

It might get even more reviews when published...

**Comment by haacked** [comment]
selfie-0

**Pull request merged**
