### PR TITLE
Feature/uk version

### PR DESCRIPTION
**Pull request by alexandrtovmach**
- added UK(Ukrainian) translation

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@shatokhinvlad, could you take a look and review it. Thanks.

**Comment by alexandrtovmach** [comment]
@mojombo @indirect @isaacs @seratch 
Hello, could you take a look on this PR. Thanks

**Comment by indirect** [comment]
@alexandrtovmach thanks for writing this. is there someone else who speaks Ukranian who could review your translation?

**Comment by alexandrtovmach** [comment]
@indirect Yes, sure. I've asked @shatokhinvlad, but will ping other developers

**Comment by chulanovskyi** [comment]
Hi @indirect ! @alexandrtovmach had asked me to review the translation that he had done. 

After in depth comparison with the original I definitely can summarize that it has a full compliance with a main thought, it is easy to read and understand the core principles of versioning system.

**Comment by shatokhinvlad** [comment]
Hi @indirect! 
I've started review of the @alexandrtovmach's translation too. But due to the lack of free time review is not completed yet.  
So, I've made PR, where "Semantic Versioning Specification (SemVer)" chapter is completed. See https://github.com/alexandrtovmach/semver.org/commit/3dce18887a4c6437a97d6b013990cddd8fd67440

@alexandrtovmach, @chulanovskyi, - would you take a look on that PR too?

**Comment by alexandrtovmach** [comment]
@shatokhinvlad let's continue discussion about your PR directly in their thread

**Comment by alexandrtovmach** [comment]
@indirect A few developers already checked the translation, so probably we can merge it to master and then if someone will find mistakes go forward with other PR's?

**Comment by indirect** [comment]
@alexandrtovmach sure. thanks for submitting!

**Pull request merged**
