### PR TITLE
Add Catalan translation

### PR DESCRIPTION
**Pull request by mikaku**
Please, at your convenience, consider adding the Catalan translation.
Thanks.

### CODE REVIEW

**Comment by haacked** [comment]
I can't read Catalan so could you find someone to double check your translation? Thanks!

**Comment by mikaku** [comment]
Doesn't Google Translate work for you?
:wink: 

OK, I'll look for someone.

**Comment by ClonicaNet** [comment]
Looks good to me.

**Comment by mikaku** [comment]
@joansanfeliu and @MiriamAparicio, can you, please, also check my translation?
Thanks.

**Comment by MiriamAparicio** [comment]
Looks good to me too.

**Comment by haacked** [comment]
Thanks!

**Pull request merged**
