### PR TITLE
Update v2.0.0.md

### PR DESCRIPTION
**Pull request by codeoD**
The correct word in chinese is '部分' not '部份'.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@codeoD Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by codeoD** [comment]
Sorry，I don't know another people whose mother language is chinese in the contributors.

**Comment by alexandrtovmach** [comment]
@Wildwizard404 @keqingrong @kewang @Lxxyx Could you help with review?

**Comment by alexandrtovmach** [comment]
@Wildwizard404 @keqingrong @kewang @Lxxyx Friendly reminder :upside_down_face:

**Review by Lxxyx — APPROVED** [review]

**Pull request merged**
