### PR TITLE
just updated a little bit

### PR DESCRIPTION
**Pull request by shivamkore**

### CODE REVIEW

**Comment by Amirnateghi1** [comment]
بروزرسانی شود  چطوری

**Review by Amirnateghi1 — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@shivamkore @Amirnateghi1 Why do you think these changes are reasonable?

**Review by alexandrtovmach — CHANGES_REQUESTED** [review]
I'm not sure about this formatting updates

**Comment by AdmiringWorm** [comment]
@alexandrtovmach this PR, as well as the PR #295, is most likely part of the spam pull requests that was opened to several open-source repositories on GitHub in the beginning of October, with the sole goal to either annoy people, or to get a free t-shirt as part of [hacktoberfest](https://hacktoberfest.digitalocean.com/).

As this seems to be an invalid contribution, I recommend closing this PR and mark it with an `invalid` label so it won't be taken into account towards their goal (only needed for pull requests opened on or before October 3rd, and is younger than 14 days).

**Comment by alexandrtovmach** [comment]
@AdmiringWorm Thank you for pay attention! :warning:

**Comment by Amirnateghi1** [comment]
Updated September 2020

**Comment by Amirnateghi1** [comment]
@AdmiringWorm

**Pull request closed without merging**
