### PR TITLE
Added kabyle translation for v2.0.0 spec.

### PR DESCRIPTION
**Pull request by nabil509**
This is a translation of SemVer specs to Kabyle language. Kabyle ISO-639-3 code is "kab". Please merge my Pull Request to allow kabyle developers to use and benefit from SemVer specs.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@nabil509 Thanks for contribution. Do you know any native speaker who can review these changes?

**Comment by nabil509** [comment]
@alexandrtovmach Thank you for reply. Yes, I collaborate with a group of native speaker localizers. I ask someone to review changes ASAP.

**Comment by MohammedBelkacem** [comment]
@nabil509  Thanks for your job. The translation seems good. 
@alexandrtovmach, I'm the L10N manager for the kab locale at Mozilla and LibreOffice. The translation seems good. We can merge it.

**Comment by alexandrtovmach** [comment]
@mozillakab Thanks for review :+1: 
@nabil509 Could you resolve conflicts?

**Comment by nabil509** [comment]
@alexandrtovmach Done!

**Pull request merged**
