### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by t32k**
Hi! :)
This is the Japanese translation of Semantic Versioning 2.0.0.

### CODE REVIEW

**Comment by haacked** [comment]
Domo Arigato Gozaimasu!

I'm not capable of reviewing the translation. Could you help find someone to review it?

**Comment by t32k** [comment]
:+1:  OK.
Please review it. @studiomohawk , @1000ch , @hiloki

**Comment by 1000ch** [comment]
@t32k Please check sent pull request :)
https://github.com/t32k/semver.org/pull/2

**Comment by studiomohawk** [comment]
@Haacked @t32k 
I've already reviewed the translated content before @t32k pull requested.
So I'd say this pull request is good for me!

**Comment by e-jigsaw** [comment]
+1

**Comment by hiloki** [comment]
+1

**Comment by t32k** [comment]
@Haacked 
Everybody has done, so please merge it if you want. :)

**Comment by haacked** [comment]
selfie-0

**Pull request merged**
