### PR TITLE
1.0.0 beta

### PR DESCRIPTION
**Pull request by theory**
Ref mojombo/semver.org#52.

### CODE REVIEW

**Comment by theory** [comment]
Wanted to diff v1.0.0 to v2.0.0, but I think this needs to be merged, first…

**Comment by theory** [comment]
Or at least tag v1.0.0, I guess.

**Comment by haacked** [comment]
Ok, so it looks like I need to tag the following commits with `v1.0.0`:
- mojombo/semver.org 79343bf9304f210f9949de8d4a1fdf0e1662f32c
- mojombo/semver [ec80195ed310aab3ae1f1ce797b7ba88b4246d27](https://github.com/mojombo/semver/blob/ec80195ed310aab3ae1f1ce797b7ba88b4246d27)

Does that look right to you?

**Comment by theory** [comment]
The semver.org one looks right; no bloody idea about the semver one, though. So, sure, go for it. :-)

I also think these should be tagged `v1.0.0-beta1`:
- mojombo/semver/38db63f21848bfce2136977cf67856a31388dab4
- mojombo/semver.org/a16c419f09b5c5a26320317fcd331264daae16ef

Thanks for getting this stuff all cleaned up!

**Comment by haacked** [comment]
@theory  shouldn't it just be `v1.0.0-beta`? Did we have more than one beta? We have the benefit of retrospect now. :)

**Comment by haacked** [comment]
Ok, I made these changes.

**Pull request merged**
