### PR TITLE
Type error in Italin translation (it)

### PR DESCRIPTION
**Pull request by Belingheri**
In italian language a statement can not end with the word `e`, in this case i suppose is typing error.

### CODE REVIEW

**Comment by JohnTitor** [comment]
@taringamberini Seems you contributed the Italian translation in the past, could you review this PR?

**Comment by taringamberini** [comment]
@JohnTitor the changes made to the italian version by @Belingheri are correct and acceptable.

In italian bullet lists don't end with an "and", usually they end with a semicolon but on the web the semicolon is usually omitted for better readability.

These changes can be merged.

**Comment by Belingheri** [comment]
@JohnTitor the PR is now ok for the merge?
thank you

**Review by JohnTitor — APPROVED** [review]
Sorry, seems I added the reaction but didn't merge. Thanks both for the review and contribution!

**Pull request merged**
