### PR TITLE
Style fix for zh-TW page

### PR DESCRIPTION
**Pull request by wmh**
I have made some change to zh-TW page. It looks better now.

### CODE REVIEW

**Comment by haacked** [comment]
Can you post a screenshot with before and after so we can see the change? Thanks!

**Comment by wmh** [comment]
Before

After

**Comment by haacked** [comment]
Ok, I'm probably not a good judge of which one is better so I'll trust your judgment. Thanks!

**Comment by wmh** [comment]
Thanks :smile:

**Pull request merged**
