### PR TITLE
Adjust RFC keywords in zh-TW

### PR DESCRIPTION
**Pull request by danny0838**
Note: this patch is based on #299 and #300.

### CODE REVIEW

**Review by IanChen83 — APPROVED** [review]
As a native speaker, I confirm that the updated version accurately reflects the english version.

**Comment by vrabe** [comment]
I suggest leaving one PR open and closing other PRs.

**Comment by danny0838** [comment]
@alexandrtovmach Hello, is there still something to consider? Do we need to involve more native speakers for review?

**Comment by alexandrtovmach** [comment]
@danny0838 Thanks for a ping. One review is enough

**Pull request merged**
