### PR TITLE
[zh-CN] Add translation of Backus–Naur Form Grammar

### PR DESCRIPTION
**Pull request by asmpg**
As #330 has improved typesetting and update to latest source ,  I just add translations of the  **Backus–Naur** part.

### CODE REVIEW

**Comment by JohnTitor** [comment]
#330 made a merge conflict, could you resolve it?

**Comment by LaoshuBaby** [comment]
I'm a native speaker of Simplified Chinese and live in Mainland of China, here is my advice of this PR, although I'm not maintainer of this repository: @JohnTitor 

# **Reject**, or at least re-create a new PR only contain Backus–Naur part.

图片

----

Here I made the full conflict diff of both #334 and #330 version, I based on 330 branch, the `index.md`(In green colour) is 330's version and `conflict.md`(In red colour) is 334 version

图片
The 1st, "透过" is zh-TW's word usage. And "来实现" isn't appear in English version's "This may
consist of documentation or be enforced by the code itself."

图片
2nd, "document" translated to "文档" is better.

图片
图片
3th, 330 version more fit English source text's layout.

图片
4th, "专案" is also a zh-TW translation of "project", we use "项目" in Mainland of China.

图片
5th, 334 version lost a full paragraph's translation.

For those all reason I support 330 version, which is merged before, will fit Mainland's using habit more better.
But the core point is that 334 translate a code block:

图片

In my opinion, the code block is a independent whole part and can't be change partly, and I counted all localization that have this Backus–Naur part:

**11** language have this part: bg/de/es/hy/ja/ko/nl/ro/uk/zh-CN(330)/zh-TW

**2** language translate text in code block: es/ko 

so, only 18% done that, for consistency, I think zh-CN should keep English version. But if this was rejected I'll also feel some pity, and those developer who don't want to read English will feel frustrated.

Maybe this need a new issue or call for other S-Chinese translator in this repository to vote.

**Comment by LaoshuBaby** [comment]
Besides I must say, even if this is allowed, 334's translation may still not localized enough.

es:

图片


ko:

图片

Both of them translate every English words.

**Review by LaoshuBaby — CHANGES_REQUESTED** [review]
For Chinese reader:

我倾向于拒绝

一是大量地区词错误与缺失文本
二是关于是否应翻译BNF内文本尚需共识，而且这段翻译的也不够完全

**Comment by JohnTitor** [comment]
I didn't look at the PR closely but yeah, we generally shouldn't translate BNF, I described the reason here: https://github.com/semver/semver.org/pull/364#issuecomment-1193099400

@asmpg I'm going to close with the above reason but if you believe translating it makes much sense, feel free to leave a comment. Thanks for your contribution anyway!

**Pull request closed without merging**
