### PR TITLE
Add missing word

### PR DESCRIPTION
**Pull request by Nesper94**

### CODE REVIEW

**Comment by JohnTitor** [comment]
@yajo @DarkGhostHunter Could you review this?

**Review by DarkGhostHunter — APPROVED** [review]

**Comment by JohnTitor** [comment]
Well, I didn't notice this edited the same line as #347, that PR removed "que" but this PR adds "es" after it, which is correct?

**Comment by Nesper94** [comment]
Hi @JohnTitor, both are correct, you can keep version from #347.

**Comment by yajo** [comment]
Yes

**Comment by JohnTitor** [comment]
Thanks for clarifying! Going to close then.

**Pull request closed without merging**
