### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by mnbvcxz010308**
* Added Hindi transaltion support for #198

### CODE REVIEW

**Comment by haacked** [comment]
Thanks! Do you know someone who can double check your translation? I unfortunately cannot read Hindi.

**Comment by mnbvcxz010308** [comment]
Okay. Searching ..

**Comment by mnbvcxz010308** [comment]
@priyankabhalekar93 Please review this. 
@Haacked  Please add @priyankabhalekar93 as a reviewer. She can read Hindi.

**Comment by haacked** [comment]
Anyone can review a PR, I don’t need to add her as a reviewer.

**Review by BoDawg2276 — APPROVED** [review]

**Comment by haacked** [comment]
Thanks!

**Pull request merged**
