### PR TITLE
[lang/sk] add spec file

### PR DESCRIPTION
**Pull request by nekomajin**

### CODE REVIEW

**Comment by nekomajin** [comment]
@tomasko126 @martinrotter @Kynio89 @ingbrzy
Hello you. We need for this project Slovak speaking people. Would you please check whether the translation of [this](https://github.com/mojombo/semver.org/blob/gh-pages/index.md) file compared with [this](https://github.com/nekomajin/semver.org/blob/e04c6a153c43659074ccd57110b3d728172bb91a/lang/sk/index.md) and [this](https://github.com/nekomajin/semver.org/blob/e04c6a153c43659074ccd57110b3d728172bb91a/lang/sk/spec/v2.0.0.md) file (actually the same) is valid? You would help us so much further.

**Comment by martinrotter** [comment]
I checked the Czech file. I would rate the translations as 8/10. They are just fine. Some sentences are translated little "robotically", but nearly all Czech people who do not know English perfectly do this. I would say that for given purpose, the translation is OK.

**Comment by nekomajin** [comment]
@martinrotter ok, thanks. Please feel free to fork and push your suggestion. Any improvement is welcome.

**Comment by haacked** [comment]
Thanks!

**Pull request merged**
