### PR TITLE
Minor Dutch improvement.

### PR DESCRIPTION
**Pull request by niekvangalen**
@alexandrtovmach could you process this minor change?

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@niekvangalen Thanks for contribution, but could you ask some native speaker for at least one review?

**Comment by alexandrtovmach** [comment]
I can't approve and merge this PR by my own, because I can't read what actually changed =)

**Review by Tieske — APPROVED** [review]
This is fine (native speaker here)

**Comment by niekvangalen** [comment]
Thanks @Tieske!

**Comment by alexandrtovmach** [comment]
Thank you both for contribution!

**Pull request merged**
