### PR TITLE
Added "Running locally" section to README.

### PR DESCRIPTION
**Pull request by m-aciek**
Instructions on how to run the site locally.

### CODE REVIEW

**Comment by jwdonahue** [comment]
@m-aciek, how was this tested?

**Comment by m-aciek** [comment]
@jwdonahue, on Linux Ubuntu 17.10.

**Comment by jwdonahue** [comment]
@m-aciek, where you tested it tells me nothing about how you tested it. What exactly did you do to test your changes?

**Comment by m-aciek** [comment]
I've followed [Setting up your GitHub Pages site locally with Jekyll](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) GitHub tutorial: Requirements, Step 2.1 and Step 4. (I've had the repository already [cloned](https://help.github.com/articles/cloning-a-repository/).)

If you want me to specify anything further, feel free to ask.

**Comment by m-aciek** [comment]
@stevegomez17
> Wow

**Comment by haacked** [comment]
Thanks! There's probably more details needed (such as for folks on Windows) but we'll let them figure it out for now. If anyone else wants to contribute more details, it'd be appreciated.

**Pull request merged**
