### PR TITLE
Armenian Translation

### PR DESCRIPTION
**Pull request by lanycrost**
This is Armenian translation for SemVer 2.0.0, 2.0.0-rc.2 and 2.0.0-rc.1

### CODE REVIEW

**Comment by lanycrost** [comment]
Guys, my PR still actual, write me something.

**Comment by alexandrtovmach** [comment]
@lanycrost Thanks for contribution. Do you know any native speaker who can review these changes? You added all contributors to reviewers, but I believe there are no one who speak Armenian 😄

**Comment by tigransimonyan** [comment]
Hey.
I am a native speaker and I think the translation is correct.

**Comment by alexandrtovmach** [comment]
Thanks @tigransimonyan for review

**Pull request merged**
